# Generated by Django 5.0 on 2024-02-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
    ]
