# Generated by Django 5.0 on 2024-01-22 13:52

import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='属性名称')),
                ('value', models.CharField(max_length=255, verbose_name='属性值')),
            ],
            options={
                'verbose_name': '产品属性',
                'verbose_name_plural': '产品属性',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='产品描述')),
                ('sku', models.CharField(default=products.models.generate_default_sku, max_length=50, unique=True, verbose_name='SKU 编号')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='产品图片')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='折扣价格')),
                ('is_discounted', models.BooleanField(default=False, verbose_name='是否打折')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='是否有库存')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='重量')),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True, verbose_name='尺寸')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='产品状态')),
                ('categories', models.ManyToManyField(blank=True, default=['Unclassified'], related_name='products', to='categories.category', verbose_name='产品分类')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier', verbose_name='供应商')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('attributes', models.ManyToManyField(blank=True, related_name='products', to='products.productattribute', verbose_name='产品属性')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
    ]
