# Generated by Django 5.0 on 2024-02-29 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_user'),
        ('suppliers', '0002_supplier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attr',
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier', verbose_name='供应商'),
        ),
    ]
